# sparql query to get general information of special collections in the knowledge graph:

PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT 
    ?inst
    ?name
    ?type
    ?website
    ?founding_date

WHERE {
    ?inst a schema:Organization .

    ?inst schema:name ?name .
    ?inst schema:additionalType ?type .
    OPTIONAL {
    ?inst schema:url ?website .
    }
    OPTIONAL {
    ?inst schema:foundingDate ?founding_date .
    }
    FILTER(REGEX(STR(?inst), "https://ror.org/"))
}
