# sparql query to get resources (publications, people, institutes, projects, events) linked to special collections in the knowledge graph:

PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?s ?resource
WHERE {
    ?s a dcat:Catalog .
    ?s dcat:resource ?resource .
}